language: java
jdk: openjdk13
services: postgresql
before_install: psql -c 'CREATE DATABASE cgi_platypi_test;' -U postgres
install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -V
script: mvn clean test
after_success: bash <(curl -s https://codecov.io/bash)
env:
  global:
    - CODECOV_TOKEN=131d2783-0d10-4f79-89a3-2572ed2eca76
